### ISSUE TITLE
Tracking Known Issues

### ISSUE THREAD

**Issue by GarrettGraham** [GarrettGraham/TheYogiMe#4]
- [ ] need to customize the styling of the form template that I created
  - [x] set the font color to white
  -  make it responsive
- bind the information so that the info is being saved to firebase
  - [ ] got the form to be sent through fireform
- [x] make the poses nav responsive
- [x] center the videos in the center of the page
- [ ] change the hover background on the nav buttons
